me: Run Java Tests

on:
    push:
          branches:
                  - main
                    pull_request:
                          branches:
                                  - main
                                    schedule:
                                          - cron: '0 2 * * *'  # Runs every day at 2 AM UTC

                                            jobs:
                                                test:
                                                      runs-on: ubuntu-latest

                                                          steps:
                                                                  - name: Checkout code
                                                                          uses: actions/checkout@v4

                                                                                - name: Set up JDK 19
                                                                                        uses: actions/setup-java@v4
                                                                                                with:
                                                                                                            java-version: '19'
                                                                                                                      distribution: 'temurin'

                                                                                                                            - name: Build and run tests
                                                                                                                                    run: mvn clean test

                                                                                                                                          - name: Upload Surefire test reports
                                                                                                                                                  if: always()
                                                                                                                                                          uses: actions/upload-artifact@v4
                                                                                                                                                                  with:
                                                                                                                                                                              name: surefire-reports
                                                                                                                                                                                        path: target/surefire-reports
